// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: voucher/voucherpb/voucher.proto

package voucherpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Voucher struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CustomerId string `protobuf:"bytes,1,opt,name=customerId,proto3" json:"customerId,omitempty"`
	OrderId    string `protobuf:"bytes,2,opt,name=orderId,proto3" json:"orderId,omitempty"`
	CampaignId string `protobuf:"bytes,3,opt,name=campaignId,proto3" json:"campaignId,omitempty"`
}

func (x *Voucher) Reset() {
	*x = Voucher{}
	if protoimpl.UnsafeEnabled {
		mi := &file_voucher_voucherpb_voucher_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Voucher) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Voucher) ProtoMessage() {}

func (x *Voucher) ProtoReflect() protoreflect.Message {
	mi := &file_voucher_voucherpb_voucher_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Voucher.ProtoReflect.Descriptor instead.
func (*Voucher) Descriptor() ([]byte, []int) {
	return file_voucher_voucherpb_voucher_proto_rawDescGZIP(), []int{0}
}

func (x *Voucher) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *Voucher) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Voucher) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

type VoucherRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Voucher *Voucher `protobuf:"bytes,1,opt,name=voucher,proto3" json:"voucher,omitempty"`
}

func (x *VoucherRequest) Reset() {
	*x = VoucherRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_voucher_voucherpb_voucher_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VoucherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoucherRequest) ProtoMessage() {}

func (x *VoucherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voucher_voucherpb_voucher_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoucherRequest.ProtoReflect.Descriptor instead.
func (*VoucherRequest) Descriptor() ([]byte, []int) {
	return file_voucher_voucherpb_voucher_proto_rawDescGZIP(), []int{1}
}

func (x *VoucherRequest) GetVoucher() *Voucher {
	if x != nil {
		return x.Voucher
	}
	return nil
}

type VoucherResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CustomerId string `protobuf:"bytes,1,opt,name=customerId,proto3" json:"customerId,omitempty"`
	Value      int32  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *VoucherResponse) Reset() {
	*x = VoucherResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_voucher_voucherpb_voucher_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VoucherResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoucherResponse) ProtoMessage() {}

func (x *VoucherResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voucher_voucherpb_voucher_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoucherResponse.ProtoReflect.Descriptor instead.
func (*VoucherResponse) Descriptor() ([]byte, []int) {
	return file_voucher_voucherpb_voucher_proto_rawDescGZIP(), []int{2}
}

func (x *VoucherResponse) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *VoucherResponse) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type VoucherStreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CampaignId string `protobuf:"bytes,1,opt,name=campaignId,proto3" json:"campaignId,omitempty"`
}

func (x *VoucherStreamRequest) Reset() {
	*x = VoucherStreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_voucher_voucherpb_voucher_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VoucherStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoucherStreamRequest) ProtoMessage() {}

func (x *VoucherStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voucher_voucherpb_voucher_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoucherStreamRequest.ProtoReflect.Descriptor instead.
func (*VoucherStreamRequest) Descriptor() ([]byte, []int) {
	return file_voucher_voucherpb_voucher_proto_rawDescGZIP(), []int{3}
}

func (x *VoucherStreamRequest) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

type VoucherStreamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CustomerId string `protobuf:"bytes,1,opt,name=customerId,proto3" json:"customerId,omitempty"`
	Value      int32  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *VoucherStreamResponse) Reset() {
	*x = VoucherStreamResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_voucher_voucherpb_voucher_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VoucherStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoucherStreamResponse) ProtoMessage() {}

func (x *VoucherStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voucher_voucherpb_voucher_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoucherStreamResponse.ProtoReflect.Descriptor instead.
func (*VoucherStreamResponse) Descriptor() ([]byte, []int) {
	return file_voucher_voucherpb_voucher_proto_rawDescGZIP(), []int{4}
}

func (x *VoucherStreamResponse) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *VoucherStreamResponse) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_voucher_voucherpb_voucher_proto protoreflect.FileDescriptor

var file_voucher_voucherpb_voucher_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x76, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x2f, 0x76, 0x6f, 0x75, 0x63, 0x68, 0x65,
	0x72, 0x70, 0x62, 0x2f, 0x76, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x07, 0x76, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x22, 0x63, 0x0a, 0x07, 0x56, 0x6f,
	0x75, 0x63, 0x68, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x1e, 0x0a, 0x0a, 0x63, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x49, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x49, 0x64, 0x22,
	0x3c, 0x0a, 0x0e, 0x56, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x2a, 0x0a, 0x07, 0x76, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x76, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x2e, 0x56, 0x6f, 0x75,
	0x63, 0x68, 0x65, 0x72, 0x52, 0x07, 0x76, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x22, 0x47, 0x0a,
	0x0f, 0x56, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x36, 0x0a, 0x14, 0x56, 0x6f, 0x75, 0x63, 0x68, 0x65,
	0x72, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e,
	0x0a, 0x0a, 0x63, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x63, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x49, 0x64, 0x22, 0x4d,
	0x0a, 0x15, 0x56, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x75, 0x73,
	0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x32, 0xa4, 0x01,
	0x0a, 0x0e, 0x56, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x3e, 0x0a, 0x07, 0x56, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x12, 0x17, 0x2e, 0x76, 0x6f,
	0x75, 0x63, 0x68, 0x65, 0x72, 0x2e, 0x56, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x76, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x2e, 0x56,
	0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x52, 0x0a, 0x0d, 0x56, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x12, 0x1d, 0x2e, 0x76, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x2e, 0x56, 0x6f, 0x75, 0x63,
	0x68, 0x65, 0x72, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1e, 0x2e, 0x76, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x2e, 0x56, 0x6f, 0x75, 0x63, 0x68,
	0x65, 0x72, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x30, 0x01, 0x42, 0x13, 0x5a, 0x11, 0x76, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x2f,
	0x76, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_voucher_voucherpb_voucher_proto_rawDescOnce sync.Once
	file_voucher_voucherpb_voucher_proto_rawDescData = file_voucher_voucherpb_voucher_proto_rawDesc
)

func file_voucher_voucherpb_voucher_proto_rawDescGZIP() []byte {
	file_voucher_voucherpb_voucher_proto_rawDescOnce.Do(func() {
		file_voucher_voucherpb_voucher_proto_rawDescData = protoimpl.X.CompressGZIP(file_voucher_voucherpb_voucher_proto_rawDescData)
	})
	return file_voucher_voucherpb_voucher_proto_rawDescData
}

var file_voucher_voucherpb_voucher_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_voucher_voucherpb_voucher_proto_goTypes = []interface{}{
	(*Voucher)(nil),               // 0: voucher.Voucher
	(*VoucherRequest)(nil),        // 1: voucher.VoucherRequest
	(*VoucherResponse)(nil),       // 2: voucher.VoucherResponse
	(*VoucherStreamRequest)(nil),  // 3: voucher.VoucherStreamRequest
	(*VoucherStreamResponse)(nil), // 4: voucher.VoucherStreamResponse
}
var file_voucher_voucherpb_voucher_proto_depIdxs = []int32{
	0, // 0: voucher.VoucherRequest.voucher:type_name -> voucher.Voucher
	1, // 1: voucher.VoucherService.Voucher:input_type -> voucher.VoucherRequest
	3, // 2: voucher.VoucherService.VoucherStream:input_type -> voucher.VoucherStreamRequest
	2, // 3: voucher.VoucherService.Voucher:output_type -> voucher.VoucherResponse
	4, // 4: voucher.VoucherService.VoucherStream:output_type -> voucher.VoucherStreamResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_voucher_voucherpb_voucher_proto_init() }
func file_voucher_voucherpb_voucher_proto_init() {
	if File_voucher_voucherpb_voucher_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_voucher_voucherpb_voucher_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Voucher); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_voucher_voucherpb_voucher_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VoucherRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_voucher_voucherpb_voucher_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VoucherResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_voucher_voucherpb_voucher_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VoucherStreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_voucher_voucherpb_voucher_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VoucherStreamResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_voucher_voucherpb_voucher_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_voucher_voucherpb_voucher_proto_goTypes,
		DependencyIndexes: file_voucher_voucherpb_voucher_proto_depIdxs,
		MessageInfos:      file_voucher_voucherpb_voucher_proto_msgTypes,
	}.Build()
	File_voucher_voucherpb_voucher_proto = out.File
	file_voucher_voucherpb_voucher_proto_rawDesc = nil
	file_voucher_voucherpb_voucher_proto_goTypes = nil
	file_voucher_voucherpb_voucher_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// VoucherServiceClient is the client API for VoucherService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VoucherServiceClient interface {
	//unary
	Voucher(ctx context.Context, in *VoucherRequest, opts ...grpc.CallOption) (*VoucherResponse, error)
	// stream
	VoucherStream(ctx context.Context, in *VoucherStreamRequest, opts ...grpc.CallOption) (VoucherService_VoucherStreamClient, error)
}

type voucherServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVoucherServiceClient(cc grpc.ClientConnInterface) VoucherServiceClient {
	return &voucherServiceClient{cc}
}

func (c *voucherServiceClient) Voucher(ctx context.Context, in *VoucherRequest, opts ...grpc.CallOption) (*VoucherResponse, error) {
	out := new(VoucherResponse)
	err := c.cc.Invoke(ctx, "/voucher.VoucherService/Voucher", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voucherServiceClient) VoucherStream(ctx context.Context, in *VoucherStreamRequest, opts ...grpc.CallOption) (VoucherService_VoucherStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_VoucherService_serviceDesc.Streams[0], "/voucher.VoucherService/VoucherStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &voucherServiceVoucherStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type VoucherService_VoucherStreamClient interface {
	Recv() (*VoucherStreamResponse, error)
	grpc.ClientStream
}

type voucherServiceVoucherStreamClient struct {
	grpc.ClientStream
}

func (x *voucherServiceVoucherStreamClient) Recv() (*VoucherStreamResponse, error) {
	m := new(VoucherStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// VoucherServiceServer is the server API for VoucherService service.
type VoucherServiceServer interface {
	//unary
	Voucher(context.Context, *VoucherRequest) (*VoucherResponse, error)
	// stream
	VoucherStream(*VoucherStreamRequest, VoucherService_VoucherStreamServer) error
}

// UnimplementedVoucherServiceServer can be embedded to have forward compatible implementations.
type UnimplementedVoucherServiceServer struct {
}

func (*UnimplementedVoucherServiceServer) Voucher(context.Context, *VoucherRequest) (*VoucherResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Voucher not implemented")
}
func (*UnimplementedVoucherServiceServer) VoucherStream(*VoucherStreamRequest, VoucherService_VoucherStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method VoucherStream not implemented")
}

func RegisterVoucherServiceServer(s *grpc.Server, srv VoucherServiceServer) {
	s.RegisterService(&_VoucherService_serviceDesc, srv)
}

func _VoucherService_Voucher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoucherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoucherServiceServer).Voucher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/voucher.VoucherService/Voucher",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoucherServiceServer).Voucher(ctx, req.(*VoucherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoucherService_VoucherStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(VoucherStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VoucherServiceServer).VoucherStream(m, &voucherServiceVoucherStreamServer{stream})
}

type VoucherService_VoucherStreamServer interface {
	Send(*VoucherStreamResponse) error
	grpc.ServerStream
}

type voucherServiceVoucherStreamServer struct {
	grpc.ServerStream
}

func (x *voucherServiceVoucherStreamServer) Send(m *VoucherStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _VoucherService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "voucher.VoucherService",
	HandlerType: (*VoucherServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Voucher",
			Handler:    _VoucherService_Voucher_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "VoucherStream",
			Handler:       _VoucherService_VoucherStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "voucher/voucherpb/voucher.proto",
}
